name: gsubsampling 
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - dbus=1.13.18
  - expat=2.2.10
  - fontconfig=2.13.0
  - freetype=2.10.4
  - glib=2.66.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2020.2
  - jpeg=9b
  - kiwisolver=1.3.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1i
  - pcre=8.44
  - pillow=8.0.1
  - pip=20.3.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytorch=1.7.1
  - qt=5.9.7
  - readline=8.0
  - setuptools=51.0.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - torchvision=0.8.2
  - tornado=6.1
  - typing_extensions=3.7.4.3
  - wheel=0.36.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.11.0
    - aiohttp==3.7.3
    - antlr4-python3-runtime==4.8
    - astunparse==1.6.3
    - async-timeout==3.0.1
    - attrdict==2.0.1
    - attrs==20.3.0
    - ax-platform==0.1.19
    - bayesian-optimization==1.2.0
    - beartype==0.6.0
    - botorch==0.3.3
    - cachetools==4.2.0
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.6.0
    - cma==3.0.3
    - colored==1.4.2
    - colorlog==4.6.2
    - configparser==5.0.2
    - dm-env==1.3
    - dm-tree==0.1.5
    - docker-pycreds==0.4.0
    - dominate==2.6.0
    - e2cnn==0.1.5
    - flatbuffers==1.12
    - fsspec==2021.6.0
    - future==0.18.2
    - gast==0.3.3
    - gitdb==4.0.7
    - gitpython==3.1.14
    - glfw==2.0.0
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - gpytorch==1.3.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - hydra-ax-sweeper==1.1.0rc1
    - hydra-colorlog==1.0.0
    - hydra-core==1.0.4
    - hydra-nevergrad-sweeper==1.1.0rc1
    - hydra-submitit-launcher==1.0.1
    - idna==2.10
    - imageio==2.9.0
    - importlib-resources==3.3.0
    - jinja2==2.11.2
    - joblib==0.17.0
    - jsonpatch==1.28
    - jsonpointer==2.0
    - keras-preprocessing==1.1.2
    - labmaze==1.0.3
    - lxml==4.6.2
    - markdown==3.3.3
    - markupsafe==1.1.1
    - multidict==5.1.0
    - nevergrad==0.4.2.post5
    - oauthlib==3.1.0
    - omegaconf==2.0.5
    - opencv-python==4.4.0.46
    - opt-einsum==3.3.0
    - packaging==20.9
    - pandas==1.1.5
    - pathtools==0.1.2
    - plotly==4.14.1
    - promise==2.3
    - protobuf==3.14.0
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.0
    - pyopengl==3.1.5
    - pytorch-lightning==1.3.0
    - pytz==2020.4
    - pyyaml==5.3.1
    - pyzmq==22.0.2
    - requests==2.25.0
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rsa==4.6
    - scikit-learn==0.23.2
    - scipy==1.5.4
    - seaborn==0.11.0
    - sentry-sdk==1.0.0
    - shortuuid==1.0.1
    - slot-attention==1.0.1
    - slurm-gpustat==0.0.7
    - smmap==4.0.0
    - submitit==1.1.5
    - subprocess32==3.5.4
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow-estimator==2.4.0
    - tensorflow-gpu==2.4.1
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - torchfile==0.1.0
    - torchmetrics==0.3.2
    - tqdm==4.54.1
    - typeguard==2.10.0
    - urllib3==1.26.2
    - visdom==0.1.8.9
    - wandb==0.10.27
    - websocket-client==0.57.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - yarl==1.6.3
